# Generated by Django 4.2.6 on 2024-01-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='ccalix@finkok.com.mx', max_length=254),
        ),
    ]
