# Generated by Django 4.2.6 on 2024-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_business',
            field=models.CharField(choices=[('S', 'Staff'), ('O', 'Operaciones'), ('P', 'Payroll'), ('L', 'Latin')], max_length=1, null=True),
        ),
    ]
