
SIMPLE_REPORT = """COPY (SELECT serial AS "Serie", folio AS "Folio", taxpayer_id AS "RFC Emisor", name AS "Nombre Emisor", rtaxpayer_id AS "RFC Receptor", rname AS "Nombre Receptor", uuid AS "UUID", emission_date AS "Fecha Emision", stamping_date AS "Fecha Timbrado", subtotal AS "SubTotal", total AS "Total", discount AS "Descuento", CASE WHEN status = 'P' THEN 'Pendiente' WHEN status = 'E' THEN 'Error' WHEN status = 'S' THEN 'Timbrado' WHEN status = 'C' THEN 'Cancelado' END AS "Estatus", payment_way AS "Forma De Pago", payment_method AS "Metodo De Pago", payroll_num AS "Numero de Nominas", total_per AS "Total Persepciones", total_ded AS "Total Deducciones", total_oth AS "Total Otros Pagos", notes AS "Notas" FROM core_payroll WHERE upload_id={}) TO '{}' CSV HEADER;"""
SIMPLE_REPORT_MAILS_SENDS = """COPY (SELECT serial AS "Serie", folio AS "Folio", taxpayer_id AS "RFC Emisor", name AS "Nombre Emisor", rtaxpayer_id AS "RFC Receptor", rname AS "Nombre Receptor", uuid AS "UUID", emission_date AS "Fecha Emision", stamping_date AS "Fecha Timbrado", subtotal AS "SubTotal", total AS "Total", discount AS "Descuento", CASE WHEN status = 'P' THEN 'Pendiente' WHEN status = 'E' THEN 'Error' WHEN status = 'S' THEN 'Timbrado' WHEN status = 'C' THEN 'Cancelado' END AS "Estatus", payment_way AS "Forma De Pago", payment_method AS "Metodo De Pago", payroll_num AS "Numero de Nominas", total_per AS "Total Persepciones", total_ded AS "Total Deducciones", total_oth AS "Total Otros Pagos", notes AS "Notas", email FROM core_payroll WHERE upload_id='{}' AND status='S') TO '{}' CSV HEADER;"""



HEADERS_REPORT_STAMPING = [
    "Folio",
    "CFDI:Emisor RFC",
    "CLIENTE",
    "Departamento",
    "Nombre",
    "Receptor RFC",
    "CURP",
    "Num Seguridad Social",
    "Registro Patronal",
    "Fecha Timbrado",
    "Fecha Inicial de Pago",
    "Fecha Final de Pago",
    "Periodo",
    "Tipo",
    "UUID",
    "Num Dias Pagados",
    "Periodicidad Pago",
    "Salario Diario Integral",
    "Salario Base de Cotizacion",
    "TipoPercepcion 001 Sueldos, Salarios  Rayas y Jornales",
    "",
    "TipoPercepcion 002 Gratificación Anual (Aguinaldo)",
    "",
    "TipoPercepcion 003 Participación de los Trabajadores en las Utilidades PTU",
    "",
    "TipoPercepcion 004 Reembolso de Gastos Médicos Dentales y Hospitalarios",
    "",
    "TipoPercepcion 005 Fondo de Ahorro",
    "",
    "TipoPercepcion 006 Caja de ahorro",
    "",
    "TipoPercepcion 009 Contribuciones a Cargo del Trabajador Pagadas por el Patrón",
    "",
    "TipoPercepcion 010 Premios por puntualidad",
    "",
    "TipoPercepcion 011 Prima de Seguro de vida",
    "",
    "TipoPercepcion 012 Seguro de Gastos Médicos Mayores",
    "",
    "TipoPercepcion 013 Cuotas Sindicales Pagadas por el Patrón",
    "",
    "TipoPercepcion 014 Subsidios por incapacidad",
    "",
    "TipoPercepcion 015 Becas para trabajadores y/o hijos",
    "",
    "TipoPercepcion 019 Horas extra",
    "",
    "TipoPercepcion 020 Prima dominical",
    "",
    "TipoPercepcion 021 Prima vacacional",
    "",
    "TipoPercepcion 022 Prima por antigüedad",
    "",
    "TipoPercepcion 023 Pagos por separación",
    "",
    "TipoPercepcion 024 Seguro de retiro",
    "",
    "TipoPercepcion 025 Indemnizaciones",
    "",
    "TipoPercepcion 026 Reembolso por funeral",
    "",
    "TipoPercepcion 027 Cuotas de seguridad social pagadas por el patrón",
    "",
    "TipoPercepcion 028 Comisiones",
    "",
    "TipoPercepcion 029 Vales de despensa",
    "",
    "TipoPercepcion 030 Vales de restaurante",
    "",
    "TipoPercepcion 031 Vales de gasolina",
    "",
    "TipoPercepcion 032 Vales de ropa",
    "",
    "TipoPercepcion 033 Ayuda para renta",
    "",
    "TipoPercepcion 034 Ayuda para artículos escolares",
    "",
    "TipoPercepcion 035 Ayuda para anteojos",
    "",
    "TipoPercepcion 036 Ayuda para transporte",
    "",
    "TipoPercepcion 037 Ayuda para gastos de funeral",
    "",
    "TipoPercepcion 038 Otros ingresos por salarios",
    "",
    "TipoPercepcion 039 Jubilaciones, pensiones o haberes de retiro",
    "",
    "TipoPercepcion 044 Jubilaciones, pensiones o haberes de retiro en parcialidades",
    "",
    "TipoPercepcion 045 Ingresos en acciones o títulos valor que representan bienes",
    "",
    "TipoPercepcion 046 Ingresos asimilados a salarios",
    "",
    "TipoPercepcion 047 Alimentación diferentes a los establecidos en el Art 94 último párrafo LISR",
    "",
    "TipoPercepcion 048 Habitación",
    "",
    "TipoPercepcion 049 Premios por asistencia",
    "",
    "TipoPercepcion 050 Viáticos",
    "",
    "TipoPercepcion 051 Pagos por gratificaciones, primas, compensaciones, recompensas u otros a extrabajadores derivados de jubilación en parcialidades",
    "",
    "TipoPercepcion 052 Pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de resoluciones judicial o de un laudo",
    "",
    "TipoPercepcion 053 Pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de resoluciones judicial o de un laudo",
    "",
    "TipoDeduccion 001 Seguridad social",
    "TipoDeduccion 002 ISR",
    "TipoDeduccion 003 Aportaciones a retiro, cesantía en edad avanzada y vejez.",
    "TipoDeduccion 004 Otros",
    "TipoDeduccion 005 Aportaciones a Fondo de vivienda",
    "TipoDeduccion 006 Descuento por incapacidad",
    "TipoDeduccion 007 Pensión alimenticia",
    "TipoDeduccion 008 Renta",
    "TipoDeduccion 009 Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores",
    "TipoDeduccion 010 Pago por crédito de vivienda",
    "TipoDeduccion 011 Pago de abonos INFONACOT",
    "TipoDeduccion 012 Anticipo de salarios",
    "TipoDeduccion 013 Pagos hechos con exceso al trabajador",
    "TipoDeduccion 014 Errores",
    "TipoDeduccion 015 Pérdidas",
    "TipoDeduccion 016 Averías",
    "TipoDeduccion 017 Adquisición de artículos producidos por la empresa o establecimiento",
    "TipoDeduccion 018 Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro",
    "TipoDeduccion 019 Cuotas sindicales",
    "TipoDeduccion 020 Ausencia (Ausentismo)",
    "TipoDeduccion 021 Cuotas obrero patronales",
    "TipoDeduccion 022 Impuestos Locales",
    "TipoDeduccion 023 Aportaciones voluntarias",
    "TipoDeduccion 024 Ajuste en Gratificación Anual (Aguinaldo) Exento",
    "TipoDeduccion 025 Ajuste en Gratificación Anual (Aguinaldo) Gravado",
    "TipoDeduccion 026 Ajuste en Participación de los Trabajadores en las Utilidades PTU Exento",
    "TipoDeduccion 027 Ajuste en Participación de los Trabajadores en las Utilidades PTU Gravado",
    "TipoDeduccion 028 Ajuste en Reembolso de Gastos Médicos Dentales y Hospitalarios Exento",
    "TipoDeduccion 029 Ajuste en Fondo de ahorro Exento",
    "TipoDeduccion 030 Ajuste en Caja de ahorro Exento",
    "TipoDeduccion 031 Ajuste en Contribuciones a Cargo del Trabajador Pagadas por el Patrón Exento",
    "TipoDeduccion 032 Ajuste en Premios por puntualidad Gravado",
    "TipoDeduccion 033 Ajuste en Prima de Seguro de vida Exento",
    "TipoDeduccion 034 Ajuste en Seguro de Gastos Médicos Mayores Exento",
    "TipoDeduccion 035 Ajuste en Cuotas Sindicales Pagadas por el Patrón Exento",
    "TipoDeduccion 036 Ajuste en Subsidios por incapacidad Exento",
    "TipoDeduccion 037 Ajuste en Becas para trabajadores y/o hijos Exento",
    "TipoDeduccion 038 Ajuste en Horas extra Exento",
    "TipoDeduccion 039 Ajuste en Horas extra Gravado",
    "TipoDeduccion 040 Ajuste en Prima dominical Exento",
    "TipoDeduccion 041 Ajuste en Prima dominical Gravado",
    "TipoDeduccion 042 Ajuste en Prima vacacional Exento",
    "TipoDeduccion 043 Ajuste en Prima vacacional Gravado",
    "TipoDeduccion 044 Ajuste en Prima por antigüedad Exento",
    "TipoDeduccion 045 Ajuste en Prima por antigüedad Gravado",
    "TipoDeduccion 046 Ajuste en Pagos por separación Exento",
    "TipoDeduccion 047 Ajuste en Pagos por separación Gravado",
    "TipoDeduccion 048 Ajuste en Seguro de retiro Exento",
    "TipoDeduccion 049 Ajuste en Indemnizaciones Exento",
    "TipoDeduccion 050 Ajuste en Indemnizaciones Gravado",
    "TipoDeduccion 051 Ajuste en Reembolso por funeral Exento",
    "TipoDeduccion 052 Ajuste en Cuotas de seguridad social pagadas por el patrón Exento",
    "TipoDeduccion 053 Ajuste en Comisiones Gravado",
    "TipoDeduccion 054 Ajuste en Vales de despensa Exento",
    "TipoDeduccion 055 Ajuste en Vales de restaurante Exento",
    "TipoDeduccion 056 Ajuste en Vales de gasolina Exento",
    "TipoDeduccion 057 Ajuste en Vales de ropa Exento",
    "TipoDeduccion 058 Ajuste en Ayuda para renta Exento",
    "TipoDeduccion 059 Ajuste en Ayuda para artículos escolares Exento",
    "TipoDeduccion 060 Ajuste en Ayuda para anteojos Exento",
    "TipoDeduccion 061 Ajuste en Ayuda para transporte Exento",
    "TipoDeduccion 062 Ajuste en Ayuda para gastos de funeral Exento",
    "TipoDeduccion 063 Ajuste en Otros ingresos por salarios Exento",
    "TipoDeduccion 064 Ajuste en Otros ingresos por salarios Gravado",
    "TipoDeduccion 065 Ajuste en Jubilaciones, pensiones o haberes de retiro en una sola exhibición Exento ",
    "TipoDeduccion 066 Ajuste en Jubilaciones, pensiones o haberes de retiro en una sola exhibición Gravado",
    "TipoDeduccion 067 Ajuste en Pagos por separación Acumulable",
    "TipoDeduccion 068 Ajuste en Pagos por separación No acumulable",
    "TipoDeduccion 069 Ajuste en Jubilaciones, pensiones o haberes de retiro en parcialidades Exento",
    "TipoDeduccion 070 Ajuste en Jubilaciones, pensiones o haberes de retiro en parcialidades Gravado",
    "TipoDeduccion 071 Ajuste en Subsidio para el empleo (efectivamente entregado al trabajador)",
    "TipoDeduccion 072 Ajuste en Ingresos en acciones o títulos valor que representan bienes Exento",
    "TipoDeduccion 073 Ajuste en Ingresos en acciones o títulos valor que representan bienes Gravado",
    "TipoDeduccion 074 Ajuste en Alimentación Exento",
    "TipoDeduccion 075 Ajuste en Alimentación Gravado",
    "TipoDeduccion 076 Ajuste en Habitación Exento",
    "TipoDeduccion 077 Ajuste en Habitación Gravado",
    "TipoDeduccion 078 Ajuste en Premios por asistencia",
    "TipoDeduccion 079 Ajuste en Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados.",
    "TipoDeduccion 080 Ajuste en Viáticos gravados",
    "TipoDeduccion 081 Ajuste en Viáticos (entregados al trabajador)",
    "TipoDeduccion 082 Ajuste en Fondo de ahorro Gravado",
    "TipoDeduccion 083 Ajuste en Caja de ahorro Gravado",
    "TipoDeduccion 084 Ajuste en Prima de Seguro de vida Gravado",
    "TipoDeduccion 085 Ajuste en Seguro de Gastos Médicos Mayores Gravado",
    "TipoDeduccion 086 Ajuste en Subsidios por incapacidad Gravado",
    "TipoDeduccion 087 Ajuste en Becas para trabajadores y/o hijos Gravado",
    "TipoDeduccion 088 Ajuste en Seguro de retiro Gravado",
    "TipoDeduccion 089 Ajuste en Vales de despensa Gravado",
    "TipoDeduccion 090 Ajuste en Vales de restaurante Gravado",
    "TipoDeduccion 091 Ajuste en Vales de gasolina Gravado",
    "TipoDeduccion 092 Ajuste en Vales de ropa Gravado",
    "TipoDeduccion 093 Ajuste en Ayuda para renta Gravado",
    "TipoDeduccion 094 Ajuste en Ayuda para artículos escolares Gravado",
    "TipoDeduccion 095 Ajuste en Ayuda para anteojos Gravado",
    "TipoDeduccion 096 Ajuste en Ayuda para transporte Gravado",
    "TipoDeduccion 097 Ajuste en Ayuda para gastos de funeral Gravado",
    "TipoDeduccion 098 Ajuste a ingresos asimilados a salarios gravados",
    "TipoDeduccion 099 Ajuste a ingresos por sueldos y salarios gravados",
    "TipoDeduccion 100 Ajuste en Viáticos exentos",
    "TipoDeduccion 101 ISR Retenido de ejercicio anterior",
    "TipoDeduccion 102 Ajuste a pagos por gratificaciones, primas, compensaciones, recompensas u otros a extrabajadores derivados de jubilación en parcialidades, gravados",
    "TipoDeduccion 103 Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de una resolución judicial o de un laudo gravados",
    "TipoDeduccion 104 Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de una resolución judicial o de un laudo exentos",
    "TipoDeduccion 105 Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de una resolución judicial o de un laudo gravados",
    "TipoDeduccion 106 Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de una resolución judicial o de un laudo exentos",
    "TipoDeduccion 107 Ajuste al Subsidio Causado",
    "TipoOtroPago 001 Reintegro de ISR pagado en exceso (siempre que no haya sido enterado al SAT).",
    "TipoOtroPago 002 Subsidio para el empleo (efectivamente entregado al trabajador).",
    "TipoOtroPago 003 Viáticos (entregados al trabajador).",
    "TipoOtroPago 004 Aplicación de saldo a favor por compensación anual.",
    "TipoOtroPago 005 Reintegro de ISR retenido en exceso de ejercicio anterior (siempre que no haya sido enterado al SAT).",
    "TipoOtroPago 006 Alimentos en bienes (Servicios de comedor y comida) Art 94 último párrafo LISR.",
    "TipoOtroPago 007 ISR ajustado por subsidio.",
    "TipoOtroPago 008 Subsidio efectivamente entregado que no correspondía (Aplica sólo cuando haya ajuste al cierre de mes en relación con el Apéndice 7 de la guía de llenado de nómina).",
    "TipoOtroPago 009 Reembolso de descuentos efectuados para el crédito de vivienda.",
    "TipoOtroPago 999 Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados.",
    "Percepciones Total Gravado",
    "Percepciones Total Exento",
    "Deducciones Total",
    "OtrosPagos Total",
    "Total",
    "Estado",
    "Version"
]

SUBHEADERS_REPORT_STAMPING = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "ImporteExento",
    "ImporteGravado",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
]


NOTIFICATIONS = {
  'title': {
    'N': 'Tienes un nuevo comprobante fiscal %s',
    'V': 'Su comprobante %s ha sido a marcada como valida',
    'E': 'Se le ha asignado una fecha al comprobante %s',
    'P': 'Se ha subido un recibo de pago apara el comprobante %s',
    'F': 'El comprobante %s sido pagada',
    'R': 'El comprobante %s fue rechazado',
    'C': 'El comprobante %s ha sido cancelado',
  },
  'message': {
    'N': 'Proveedor seguro valido satisfactoriamente este comprobante. No pierdas tiempo checando tu comprobante fiscal',
    'V': 'Proveedor seguro cerifico su comprobante y es totalmente valido. No pierdas tiempo checando tu comprobante fiscal',
    'E': 'se le ha asignado fecha de pago a este comprobante. No pierdas tiempo checando tu comprobante fiscal',
    'P': 'Se ha subido un comprobante de pago para este comprobante. No pierdas tiempo checando tu comprobante fiscal',
    'F': 'el comprobante ha sido como marcado. No pierdas tiempo checando tu comprobante fiscal',
    'R': 'Tu comprobante ha sido rechazado. Adjuntamos un reporte de las validaciones que realizamos',
    'C': 'Proveedor seguro ha detectado que el comprobante ha sido cancelado.',
  },
}